name: Run Tests
on: [push]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'sbt'
    - name: sbt update
      run: sbt update
    - name: sbt test
      run: sbt test
  plugin_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'sbt'
    - name: sbt update
      run: sbt update
    - name: sbt publishLocal
      run: sbt publishLocal
    - name: Run plugin tests
      run: sbt scripted
